name: Execução dos testes de integração

on:
    push:
        branches: [main, developer]
    pull_request:
        branches: [main, developer]

jobs:
    integration_tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2.2.0
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependences
              run: npm install

            - name: Run tests
              run: npm run test
